### ISSUE TITLE
Wordlist Contents?

### ISSUE THREAD

**Issue by BigB86** [bitquark/shortscan#3]
First of all I wanted to say thank you for the great tool! I was looking into using a wordlist with your shortutil tool, but I'm unsure of what the wordlist should contain. Would it be possible to include a few samples?

I'm unsure if it can contain directories like /iishelp/iis/misc/default.asp

Or the end directory like /misc/

Of if the word list can contain actual pages like admin.aspx

**Comment by bitquark** [comment]
I'm glad you're finding shortscan useful!

With regards to wordlists, shortutil will normalise any input (
terminating directory slashes will be removed, and only the last

**Comment by bitquark** [comment]
I'm glad you're finding shortscan useful! With regards to wordlists, shortutil expects a list of files or directories with no path elements, however it will normalise any input so that only the last path element will be used, and terminating directory slashes will be removed so you can throw most things at it and it'll generate somewhat sensible output. Hope that helps!

**Comment by marcelo321** [comment]
Would be cool to have a wordlist added here too to serve as an example? like top1000 dirs and files or something like that
